# Generated by Django 4.2.4 on 2023-08-08 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppning', '0004_remove_category_slug_remove_category_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='user',
        ),
    ]
