# Generated by Django 4.2.4 on 2023-08-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppning', '0006_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='original_price',
            field=models.FloatField(default=False),
        ),
    ]
